sudo: required
services:
  - docker

before_install:
  - docker build -t pranshuvinayak/test -f ./client/Dockerfile.dev ./client

script:
  - docker run pranshuvinayak/test npm test -- --coverage

after_success:
  - docker build -t pranshuvinayak/multi-client ./client
  - docker build -t pranshuvinayak/multi-nginx ./nginx
  - docker build -t pranshuvinayak/multi-server ./server
  - docker build -t pranshuvinayak/multi-worker ./worker

# Log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push the Images to Docker Hub
  - docker push pranshuvinayak/multi-client
  - docker push pranshuvinayak/multi-nginx
  - docker push pranshuvinayak/multi-server
  - docker push pranshuvinayak/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-367199001921"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $ACCESSKEYID
  secret_access_key:
secure: "$SECRETACCESSKEY"